apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejstodo
  name: nodejstodo
  namespace: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejstodo
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejstodo
    spec:
      containers:
      - image: soewailin/nodejs-todolist:ca3f0d16123e8a43864be323308ce5e6a7acff44
        name: nodejs-todolist
        resources: {}

