apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejstodo
  name: nodejstodo
  namespace: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejstodo
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejstodo
    spec:
      containers:
      - image: soewailin/nodejs-todolist:75d1f98bbf88feb3cb9800aa0d3639e16ee568e0
        name: nodejs-todolist
        resources: {}

