apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejstodo
  name: nodejstodo
  namespace: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejstodo
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejstodo
    spec:
      containers:
      - image: soewailin/nodejs-todolist:248c5828b1446acabb8fca949d8c79897d1f0c11
        name: nodejs-todolist
        resources: {}

