apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejstodo
  name: nodejstodo
  namespace: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejstodo
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejstodo
    spec:
      containers:
      - image: soewailin/nodejs-todolist:b18223b6286e14922b43399afe56a30b47589037
        name: nodejs-todolist
        resources: {}

