apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejstodo
  name: nodejstodo
  namespace: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejstodo
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejstodo
    spec:
      containers:
      - image: soewailin/nodejs-todolist:af6c11f8be6b52cd990d4192562492ffcc5b2164
        name: nodejs-todolist
        resources: {}

