apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejstodo
  name: nodesvc
  namespace: nodejs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: nodejstodo
  type: LoadBalancer

